### ISSUE TITLE
Confusing or typo text on Getting Started page

### ISSUE THREAD

**Issue by dgodongm** [dubzzz/fast-check#4631] opened 2024-01-17 20:41 UTC
## 🐛 Bug Report

The text, "Now, that you've it in your project you can start playing with it on any property." doesn't seem grammatical, particularly "...that you've it in your..." 
The comma after "Now" also seems questionable

## To Reproduce

Steps to reproduce:
Go to https://fast-check.dev/docs/introduction/getting-started/ and check text under the Simple Property header

## Expected behavior

Text should be clarified. Perhaps to:
"Now that you've integrated fast-check in your project..."

## Your environment
n/a

**Comment by dubzzz** [comment] 2024-01-17 23:39
Opened to suggestions. Please feel free to open a PR with a rephrasing that would be more natural. I'm not an English native speaker so any help to enhance the English of the documentation is more than welcomed and appreciated 🥰

**Comment by dubzzz** [comment] 2024-01-21 15:57
Cc @dgodongm

**Comment by dubzzz** [comment] 2024-01-21 22:00
Closing: not a bug. Please feel free to open a PR with your suggestion

**Closed** 2024-01-21 21:59 UTC
Labels: 🐛 Bug Report
