### ISSUE TITLE
Request for a fc.undefined<T>(arb: Arbitrary<T>): Arbitrary<T | undefined>

### ISSUE THREAD

**Issue by MaxwellBo** [dubzzz/fast-check#391] opened 2019-07-09 03:52 UTC
In much the same way as the `fc.option<T>(arb: Arbitrary<T>): Arbitrary<T | null>` function, I was wondering why there wasn't an equivalent `fc.undefined<T>(arb: Arbitrary<T>): Arbitrary<T | undefined>`.

I might open a PR for it but the [implementation](https://github.com/dubzzz/fast-check/blob/master/src/check/arbitrary/OptionArbitrary.ts) for `fc.option` looks... rather complex.

**Comment by MaxwellBo** [comment] 2019-07-09 05:02
I might have jumped the gun a bit, but I'm leaving the issue up because it might be useful for future users of the library:

```
import * as fc from 'fast-check';
import { Arbitrary } from 'fast-check';

/**
 * For either undefined or a value coming from `arb`
 * @param arb Arbitrary that will be called to generate a non null value
 */
function maybe<T>(arb: Arbitrary<T>): Arbitrary<T | undefined>;
/**
 * For either undefined or a value coming from `arb` with custom frequency
 * @param arb Arbitrary that will be called to generate a non undefined value
 * @param freq The probability to build a undefined value is of `1 / freq`
 */
function maybe<T>(arb: Arbitrary<T>, freq: number): Arbitrary<T | undefined>;
function maybe<T>(arb: Arbitrary<T>, freq?: number): Arbitrary<T | undefined> {
  return (freq ? fc.option(arb, freq) : fc.option(arb)).map(x => x || undefined);
}
```

This got me effectively what I needed.

**Comment by dubzzz** [comment] 2019-07-09 07:12
@MaxwellBo good point, `undefined` should also be one of the possible outcomes of an option-like operator.

Thinking a step further, I am wondering if what we want for `fc.option` is more like:

`fc.option(arb, { nil: undefined })`

With such construct it will cover a larger scope of nullable values.

Quick explanation for the current implementation of the option:
Today it's one of the base types of fast-check as it directly extends `Arbitrary` (most of the time, a end user code should only be using map, filter or chain but rarely extending Arbitrary).
One of the most important features of option today, is that it preserves the shrinker of the initial arbitrary and add the null value as possible shrink value for it.

**Comment by dubzzz** [comment] 2019-07-09 07:23
Just in case the issue is blocking for you, you can define the operator you want that way:

`const undefArb = (srcArb) => fc.option(srcArb).map(v => v === null? undefined : v)

**Comment by MaxwellBo** [comment] 2019-07-09 22:46
Ah awesome, I was a little concerned that an arbitrary build with a `.map` might not shrink properly. 

I ended up with 

```typescript
import * as fc from 'fast-check';
import { Arbitrary } from 'fast-check';

/**
 * For either undefined or a value coming from `arb`
 * @param arb Arbitrary that will be called to generate a non undefined value
 */
export function maybe<T>(arb: Arbitrary<T>): Arbitrary<T | undefined>;
/**
 * For either undefined or a value coming from `arb` with custom frequency
 * @param arb Arbitrary that will be called to generate a non undefined value
 * @param freq The probability to build a undefined value is of `1 / freq`
 */
export function maybe<T>(arb: Arbitrary<T>, freq: number): Arbitrary<T | undefined>;
export function maybe<T>(arb: Arbitrary<T>, freq?: number): Arbitrary<T | undefined> {
  return (freq ? fc.option(arb, freq) : fc.option(arb)).map(x => x || undefined);
}
```

as my stopgap.

**Comment by MaxwellBo** [comment] 2019-10-01 10:22
Amazing, thanks for this addition @dubzzz, just noticed it today in the VSCode autocomplete!

**Comment by dubzzz** [comment] 2019-10-02 06:57
Closing the issue as it's supposed to be fixed and released now.

Feel free to re-open

**Closed by dubzzz** 2019-10-02 06:57 UTC
Labels: ✔️ Feature Accepted, 🚀 Feature Request
