### ISSUE TITLE
Add Bucklescript bindings for Reasonml

### ISSUE THREAD

**Issue by MarcCoquand** [dubzzz/fast-check#360] opened 2019-05-12 05:05 UTC
fast-check is a very nice library. It would be even better if we could use it with Facebook's ReasonML instead of Typescript!

It might be possible to use https://github.com/rrdelaney/ReasonablyTyped to make the conversion easier.

**Comment by dubzzz** [comment] 2019-05-12 17:24
Hi @MarcCoquand,

I'll have a look to it. If the conversion works fine I will definitely go for it.

I know some other libs like jsverify comes with another package manually written to handle such typings bs-jsverify. But if the conversion can be done easily and automatically I can definitely add it into my build process.

**Comment by TheSpyder** [comment] 2019-09-27 08:13
Manual bindings are a pain, but ReasonablyTyped looks abandoned. I'm hoping to switch my ReasonML project from jsverify to fast-check sometime this year, if I do I'll work on some bindings (probably base them off bs-jsverify) and make a PR. Even if it's not complete API coverage it'll still give us something to work with!

**Comment by TheSpyder** [comment] 2020-01-08 21:07
I've written some bindings, they seem to work well, we have migrated our `bs-jsverify` tests to them and it was very easy 😁 

They're external bindings at the moment. I'll work on a PR to include them in fast-check directly so they are easier to keep up to date. Might take me a bit more time to do, I also need to make a decision about the `map` and `filter` functions (those function names are very common in reasonml code so having them in scope from my bindings can cause conflicts).

I'm currently thinking I'll put them in a dedicated module where they will conflict less. I've tried to structure the bindings fairly close to the documentation so everything is easy to find, but maybe functions from the [advanced arbitraries](https://github.com/dubzzz/fast-check/blob/master/documentation/1-Guides/AdvancedArbitraries.md) documentation can go in a separate `Derive` module 🤔

**Comment by TheSpyder** [comment] 2020-08-28 21:42
Yeah, I'm not surprised. Sorry I haven't had time to look at it since January, this year has been crazy. I can confirm however that [my bindings](https://github.com/TheSpyder/bs-fast-check) are working very well. I still consider them temporary and would prefer to contribute them eventually.

**Comment by TheSpyder** [comment] 2020-10-28 01:36
@dubzzz I've had a poke around how to include my bindings into fast-check directly and it looks like BuckleScript (now ReScript) bindings are a bit of a challenge to co-locate in the project they're binding to.

There are a few problems, but the real blocker is that ReScript doesn't have a way to use separate require paths for CJS and ES6 compile modes. It can compile in either style but the require path is fixed in the source file. This isn't a problem for external references, `require('fast-check')` and `import * from 'fast-check'` work equally well, but for internal references it would need to change from `../lib/fast-check.js` to `../lib/esm/fast-check.js`.

For the moment I'm happy to maintain my separate project and start publishing it to NPM. I also plan to discuss ways to make this easier with the ReScript team. If it later becomes possible to integrate the bindings I can lodge a PR then, if you'd like to close this issue for now.

**Comment by dubzzz** [comment] 2020-10-28 07:29
If we leave the project outside of fast-check (which seems to be a good option for the moment), you might be interested into adding a small note about it in fast-check's documentation (maybe in the Tips section or next to the compatibility table).

Please feel free to add such information.

**Comment by TheSpyder** [comment] 2020-10-28 09:35
Thanks! Once I’ve started publishing to NPM I’ll definitely do that.

**Comment by TheSpyder** [comment] 2020-10-29 23:21
I'll make a PR soon, but for now the package has been published. I decided to put a bit of effort into documenting how to use it 🙂 
https://www.npmjs.com/rescript-fast-check

**Closed** 2020-11-16 08:10 UTC
Labels: good first issue, help wanted, 🚀 Feature Request
