### ISSUE TITLE
Running `import { test, fc } from '@fast-check/jest';` results in error reading properties of undefined in jest

### ISSUE THREAD

**Issue by CMCDragonkai** [dubzzz/fast-check#4986] opened 2024-05-15 06:53 UTC
## 🐛 Bug Report

I'm trying to use the latest ESM version of `@fast-check/jest`. I got everything else working.

As soon as I try to import `import { test, fc } from '@fast-check/jest';` there seems to be some problem with some undefined property.

```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'only')

      at internalTestPropConcurrent (node_modules/@fast-check/jest/lib/esm/internals/TestPropBuilder.js:25:43)
      at internalTestProp (node_modules/@fast-check/jest/lib/esm/internals/TestPropBuilder.js:32:18)
      at node_modules/@fast-check/jest/lib/esm/jest-fast-check.js:7:25
```

Seems something isn't quite working..

## To Reproduce

Steps to reproduce:

1. Go here https://github.com/MatrixAI/js-table/pull/3
2. Try to run `npm test`

## Expected behavior

Clear and concise description of what you expected to happen.

That it just imports properly.

If you have one, please provide a minimal repository reproducing the issue on GitHub.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           | ^3.10.0 |
| node                 | v20.5.1    |
| TypeScript\*         | ^5.1.6    |

\*Only for TypeScript's users

**Comment by CMCDragonkai** [comment] 2024-05-15 06:59
This line in

```
import { it as itJest, test as testJest, jest } from '@jest/globals';
```

Doesn't work as `testJest` is `undefined`. It appears it does not exist. However `jest` does exist.

**Comment by CMCDragonkai** [comment] 2024-05-15 07:04
This is the latest version of jest. So I don't think the `@jest/globals` exports the `test` property anymore.

**Comment by dubzzz** [comment] 2024-05-15 07:28
Strange... I have some tests checking ES Module mode 🤔 (tests [here](https://github.com/dubzzz/fast-check/tree/main/packages/jest/test-bundle))
I'll check if they correctly setup Jest for such usage...

In he meantime, a shorter and minimal reproduction case could help me into investigating. Current test case is a bit too huge to start an investigation without loosing time trying to understand how the project works, is setup...

**Comment by dubzzz** [comment] 2024-05-15 07:29
I'll probably check and extend my tests to use the test and not the testProp thing so that it gets closer to my latest recommendations.

**Comment by CMCDragonkai** [comment] 2024-05-15 07:32
If you have `nix-shell`, you can just enter `nix-shell` first.

If not, an `npm install` then `npm test` should suffice.

**Comment by dubzzz** [comment] 2024-07-12 15:19
Closing, cannot repro, no minimal case provided

**Closed by dubzzz** 2024-07-12 15:19 UTC
Labels: 🐛 Bug Report

**Comment by amydevs** [comment] 2024-08-13 02:29
i think it turns out to be something to do with importing from `@jest/globals` working improperly with `@swc/jest` https://github.com/swc-project/jest/issues/120. Simply patching out the imports with `const {...} = global;` seems to work fine.

**Comment by CMCDragonkai** [comment] 2024-12-16 22:29
@dubzzz can you have a look at @amydevs fix and see if we can apply it to the repo here?

**Comment by dubzzz** [comment] 2024-12-16 22:55
Why not. Let's try. CI should warn us if it breaks something

**Comment by CMCDragonkai** [comment] 2024-12-18 06:53
Do you want a PR to just the above patch?

**Comment by dubzzz** [comment] 2024-12-18 07:41
Go ahead, yes 👍
