### ISSUE TITLE
I wish to see negative zero more often

### ISSUE THREAD

**Issue by mordae** [dubzzz/fast-check#5416] opened 2024-11-08 10:43 UTC
## 🚀 Feature Request

I would like to significantly increase the frequency with which `-0` occurs. Ideally it would typically be included with certainty from 100 runs up. It would also be nice to see infinities with certainty above certain amount of runs.

## Motivation

1. They pose an edge case and every such edge case presents an opportunity to be missed by application logic. Property based testing which focuses on edge cases helps discover more errors in shorter time. Exploring -1/-0/0/1 more thoroughly than e.g. 1234/1235/1236 will typically yield a lot more discoveries.

2. They currently appear so infrequently that they sometime pop up in a random test case never to show again for quite some time. Unstable tests are bad for automated CI/CD pipelines.

## Example

It would work by default, just discover issues like:

```javascript
> Buffer.from([-0])[0]
0
```

**Comment by dubzzz** [comment] 2024-11-08 11:17
In theory `fc.double()` does provide `-0` in regular basis (same for `fc.float()`).

Which usage is problematic on your end I don't see which arbitrary you are using?

**Comment by dubzzz** [comment] 2024-11-08 11:18
Something like:

```ts
fc.array(fc.double()).map(Buffer.from)
```

Should probably do what you're looking for.

**Comment by dubzzz** [comment] 2024-11-12 20:01
Closing for now as I cannot reproduce. Feel free to reopen if needed

**Closed by dubzzz** 2024-11-12 20:01 UTC
Labels: ❌ Can't Reproduce
