### ISSUE TITLE
Problem when mixing local project moduleResolution nodenext and a 3rd party package using fast-check

### ISSUE THREAD

**Issue by patroza** [dubzzz/fast-check#4519] opened 2023-12-06 06:42 UTC
## 🐛 Bug Report

```
Argument of
type 'typeof import(\"pj/effect-app/libs/node_modules/fast-check/lib/types/fast-check\")' is not assignable to parameter of
type 'typeof import(\"pj/effect-app/libs/node_modules/fast-check/lib/esm/types/fast-check\", { with: { \"resolution-mode\": \"import\" } })'
```

## Expected behavior

No error. probably there should only be one set of d.ts (unless there are some reasons there can't be):
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
deleted file mode 100644
index f272c80981f45dc84797c50af97fe5d2348fd188..0000000000000000000000000000000000000000
diff --git a/package.json b/package.json
index 8accb7fb8662a36944083994c78e65a2e3f32a53..7f3548d14423de586bf8e1bdc99a5ad77bb05a3e 100644
--- a/package.json
+++ b/package.json
@@ -12,7 +12,7 @@
         "default": "./lib/fast-check.js"
       },
       "import": {
-        "types": "./lib/esm/types/fast-check.d.ts",
+        "types": "./lib/types/fast-check.d.ts",
         "default": "./lib/esm/fast-check.js"
       }
     }
```
this works great so far.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           |    3.14        |
| node                 |     18.10.0       |
| TypeScript\*         |    5.3.2        |

\*Only for TypeScript's users

**Comment by dubzzz** [comment] 2023-12-17 14:30
Thanks a lot for the report, I was quite busy last week but I clearly plan to tackle this one in the coming days. The change on types has been made on purpose but the breakage is definitely not expected. I'll have to find a way to fix both issues (the one that pushed me to do this change and yours) with something 🤔

**Comment by dubzzz** [comment] 2023-12-17 14:31
By the way if you have a working and simple repro on a GitHub repo, it will help me a lot to tackle the issue quickly.

**Comment by dubzzz** [comment] 2023-12-17 14:33
It might be related to a similar report I got weeks ago: https://github.com/dubzzz/fast-check/pull/4354

**Comment by dubzzz** [comment] 2024-01-21 21:59
Closing: unable to reproduce

**Closed** 2024-01-21 21:59 UTC
Labels: 🐛 Bug Report

**Comment by patroza** [comment] 2024-03-27 14:29
@dubzzz sorry for the late response, here's the repro: https://github.com/patroza/pnpm-monorepo-boilerplate/tree/repro/dts-esm-bug

looks like it's a TS bug, but at the same time if there are two .d.ts, it is possible that under weird circumstance, both are loaded (through external dependencies and one in your own project), as such it may still be a good idea to have a shared d.ts amongst them for unique symbols, so that it doesn't run into compatibility issues.

what was the original issue you tried to solve with two separate dts?

**Comment by patroza** [comment] 2024-03-27 15:52
@dubzzz apparently it's designed that way according to Andarist, so here's instead a patch that would resolve the incompatibility between the two typedefinitions:
https://github.com/patroza/fast-check/pull/1/files

would something like that be acceptable? it applies the idea from https://github.com/dubzzz/fast-check/pull/4354#issuecomment-1859240300

**Comment by dubzzz** [comment] 2024-03-27 16:01
Hmmm sounds acceptable 🤔
We can probably give it a try

**Comment by patroza** [comment] 2024-03-28 09:01
@dubzzz when testing locally a new error appeared today, im trying to investigate
<img width="1736" alt="Screenshot 2024-03-28 at 10 01 01" src="https://github.com/dubzzz/fast-check/assets/42661/b72e4d3e-06fb-4e6f-9610-c28217798af6">

**Comment by patroza** [comment] 2024-03-28 09:36
@dubzzz ok. I apologise, I have no idea what is going on with my test setup, and why I received a positive test result before (happened twice in a row now).
The problem is not resolved, there are still problems with symbols; you have more, and now my time is also running out to look into it deeper short notice.

**Comment by patroza** [comment] 2024-03-28 09:40
@dubzzz ok. the issue with my particular test case is resolved by the changes, but the not all types are fully compatible still.

The problem is not fully resolved, there are still problems with symbols; you have more like `asyncToStringMethod` and `toStringMethod` etc, and now my time is also running out to look into it deeper short notice.
