### ISSUE TITLE
react-testing-library test is failing with fast-check when I include `fireEvent`

### ISSUE THREAD

**Issue by tobiastimm** [dubzzz/fast-check#3934] opened 2023-05-30 09:30 UTC
## 💬 Question and Help

Hello folks,

I'm struggling with a weird error message when I try to use `fast-check` and `react-testing-library` combined with `fireEvent`.

I have a simple test for showing/hiding a context menu, but surprisingly that test is failing with `fast-check` with an error message `TypeError: Cannot read properties of null (reading 'createEvent')` as soon as I use `fireEvent`.

Test w/o fast-check 
```
  it('opens a context menu on click', async () => {
    const mockProps: ContextMenuProps = {
      nickname: '',
    };

    render(<ContextMenu {...mockProps} />);

    const menuButton = await screen.findByTestId(
      'CONTEXT_MENU_BUTTON'
    );

    expect(menuButton).toBeInTheDocument();
    fireEvent.click(menuButton);

    expect(
      await screen.findByTestId('NICKNAME_BUTTON')
    ).toBeInTheDocument();
  });
```

Test with fast-check
```
const ContextMenuPropsArbitrary = fc.record({
  nickname: fc.string(),
});

it('opens a context menu on click', async () => {
    await fc.assert(
      fc
        .asyncProperty(ContextMenuPropsArbitrary, async (props: ContextMenuProps) => {
          render(<ContextMenu {...props} />);

          const menuButton = await screen.findByTestId(
            'CONTEXT_MENU_BUTTON'
          );

          expect(menuButton).toBeInTheDocument();
          fireEvent.click(menuButton);

          expect(
            await screen.findByTestId('NICKNAME_BUTTON')
          ).toBeInTheDocument();
        })
        .afterEach(cleanup)
    );
  });
```

The test is working fine w/o `fast-check`.

I don't know what I'm doing wrong here.

**Comment by dubzzz** [comment] 2023-05-30 14:08
Cannot reproduce without more context. At first glance, I'd say that fireEvent probably need to be wrapped within an `act` statement, but without a repro (for instance in a codesandbox env), I probably will not be able to give that much help.

**Comment by tobiastimm** [comment] 2023-06-07 07:53
thanks anyway for that quick reply! I will try to investigate what is causing this

**Comment by dubzzz** [comment] 2023-06-17 17:06
Closing the issue for now. Feel free to reopen whenever you want. More details would help to find out what might fail

**Closed** 2023-06-17 17:06 UTC
Labels: ❌ Can't Reproduce, 🐛 Bug Report
