### ISSUE TITLE
`fc.pre` doesn't work as expected when used with `@fast-check/ava`

### ISSUE THREAD

**Issue by ericcornelissen** [dubzzz/fast-check#4432] opened 2023-11-12 11:11 UTC
## 🐛 Bug Report

When the `fc.pre` condition doesn't hold in a `@fast-check/ava` test the test fails, but using `fc.pre` in a plain `fast-check` test (in AVA) doesn't.

## To Reproduce

Steps to reproduce:

- Install `ava`, `fast-check` and `@fast-check/ava` as dependencies
- Create the following test

  ```js
  import { testProp } from "@fast-check/ava";
  import test from "ava";
  import * as fc from "fast-check";

  test("ava + fast-check", (t) => {
    fc.assert(
      fc.property(
        fc.string({ maxLength: 20 }),
        (str) => {
          fc.pre(str.length < 10);
          t.pass();
        },
      ),
    );
  });

  testProp(
    "@fast-check/ava",
    [fc.string({ maxLength: 20 })],
    (t, str) => {
      fc.pre(str.length < 10);
      t.pass();
    },
  );
  ```

- Run the tests and observe that (consistently) `ava + fast-check` succeeds and `@fast-check/ava` fails, even though they're identical.

For your convenience, I created a more complete example at ~~[ericcornelissen/cuddly-bassoon](https://github.com/ericcornelissen/cuddly-bassoon)~~.

## Expected behavior

The two tests should behave the same. Specifically the `@fast-check/ava` behavior should match that of plain `fast-check`.

Alternatively, if this turns out to be impossible, I would expect that fact to be documented in the `@fast-check/ava` documentation.

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           | 3.13.2     |
| `@fast-check/ava`    | 1.1.6      |
| AVA                  | 5.3.1      |
| node                 | 20.0.9     |
| TypeScript\*         | n/a        |

\*Only for TypeScript's users

**Comment by dubzzz** [comment] 2023-11-13 20:41
I'll need to check deeper in the code, but from what I can see on your repro it's definitely not the expected behavior as both syntaxes should work the same way.

I'll let you know when I get an idea of the root cause of it.

**Comment by dubzzz** [comment] 2023-11-13 20:48
I have not debugged it yet, but I suspect the bug is coming from https://github.com/dubzzz/fast-check/blob/main/packages/ava/src/ava-fast-check.ts#L44. Indeed `t.try` passing might not mean success, as it can be:

- returning false and thus failure (I suspect this one fails too today)

And not passing might not mean failure:

- returning skipped and thus should skip and fails if too many skips

**Comment by ericcornelissen** [comment] 2023-11-14 22:54
Had a quick look and I think you're at least partially right, the following reproduces the bug without using `@fast-check/ava`:

```javascript
test("ava + fast-check (try)", (t) => {
  fc.assert(
    fc.property(
      fc.string({ maxLength: 20 }),
      (str) => {
        const tryResult = t.try((tt) => {
          fc.pre(str.length < 10);
          tt.pass();
        });

        if (tryResult.passed) {
          tryResult.commit();
          return true;
        }
        return false;
      },
    ),
  );
});
```

I'm _guessing_ the use of `t.try` results in the information about the error coming from `fc.pre` being lost, which fast-check [seems to somehow take into account](https://github.com/dubzzz/fast-check/blob/b48f90c8bc1a8c9cf0b2a5c31c4703f48952e183/packages/fast-check/src/check/property/Property.generic.ts#L147).

I can't think of anything obvious to avoid the problem. Not using `t.try` _would_ work, but probably break `t.plan`. Maybe inverting `t.try` and `fc.assert` could work, but that might mess with shrinking?

**Comment by dubzzz** [comment] 2023-11-17 09:04
I'm making some progress on this one. I'll continue my investigations further to fully support `pre` in that specific scenario.

**Comment by dubzzz** [comment] 2023-11-19 22:39
It should be fixed in the last published version of `@fast-check/ava`. Please feel free to reopen if it's not the case

**Comment by ericcornelissen** [comment] 2023-12-12 18:29
@dubzzz it seems there was a regression related to this due to the [v6.0.0 release of AVA](https://github.com/avajs/ava/releases/tag/v6.0.0) (the example from the original issue description replicates it for v6.0.0, unfortunately I removed the repository I had created). I'm not quite sure which of the listed breaking changes caused this...

**Comment by dubzzz** [comment] 2023-12-12 18:36
Strange... I need to dig more into it as I should have covered the issue with a test. But maybe my test sucks

**Comment by ericcornelissen** [comment] 2023-12-12 18:39
Given https://github.com/dubzzz/fast-check/pull/4521 (_only thought to check if you're already testing against the new version just now_), I don't think your test sucks because the CI seems to have failed :smile:

**Comment by dubzzz** [comment] 2023-12-12 18:42
I'll check that. Re-opening the issue

**Comment by dubzzz** [comment] 2023-12-12 18:55
>  I don't think your test sucks because the CI seems to have failed

I thought I fixed it, but I have not indeed 😂

**Comment by dubzzz** [comment] 2023-12-16 15:27
Issue found, fix on its way. Release will come soon.

**Closed** 2023-12-16 16:06 UTC
Labels: 🐛 Bug Report, ✔️ Bug Confirmed
