### ISSUE TITLE
Exceptions thrown inside fast-check, schedule aren't processed by fast-check and they not contain counterexample

### ISSUE THREAD

**Issue by krzysztofpniak** [dubzzz/fast-check#3711] opened 2023-03-29 10:09 UTC
## 🐛 Bug Report

Exceptions thrown inside fast-check, schedule aren't processed by fast-check and they not contain counterexample, seed and other metadata.

## To Reproduce

Steps to reproduce:

```js
describe('schedule', () => {
  it('should fail with fast-check counterexample', async () => {
    await fc.assert(
      fc.asyncProperty(fc.scheduler(), async s => {
        s.schedule(Promise.resolve('p1')).then(() => {
          throw new Error('some error');
        });

        await s.waitAll();
        //console.log(s.report());
      })
    );
  });
});
```

## Expected behavior
 it should print error similar to following:
```
Error: Property failed after 1 tests
{ seed: -1904276372, path: "0", endOnFailure: true }
Counterexample: [schedulerFor()`
`]
Shrunk 0 time(s)
Got error: some error
```

## Actual behavior
```
        throw new Error('asd');
              ^

Error: asd
    at /Users/johnny/js/test.spec.js:185:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0
```

## Your environment

| Packages / Softwares | Version(s) |
| -------------------- | ---------- |
| fast-check           |  3.7.1 |
| node                 |  18|

**Comment by dubzzz** [comment] 2023-03-29 18:45
I'll try to investigate it in the coming days. Thanks for the report.

This one seems to be way easier to troubleshoot than the other one you opened. I'll probably start with it as they could be linked.

**Comment by krzysztofpniak** [comment] 2023-03-29 21:02
I also think they are connected. I was investigating [first one](https://github.com/dubzzz/fast-check/issues/3704), because I wasn't sure if the problem is in my code, fast-check or react-testing library. This bug is the result of "shrinking" my code from the [first one.](https://github.com/dubzzz/fast-check/issues/3704)

**Comment by dubzzz** [comment] 2023-03-30 07:10
My investigation led me to the following idea: here the predicate never fails.

What fails is: we are firing an unhandled promise rejection that crashes node. As a consequence, node crashes while fast-check cannot intercept anything.

I confirmed the idea by doing something like:

```js
describe('schedule', () => {
  it('should fail with fast-check counterexample', async () => {
    await fc.assert(
      fc.asyncProperty(fc.scheduler(), async s => {
        s.schedule(Promise.resolve('p1')).then(() => {
          throw new Error('some error');
        });

        await s.waitAll();
        console.log('success');
      })
    );
  });
});
```

And if you run it locally you'll see:

```txt
success
...
success
C:\Users\n.dubien\Desktop\test-packages\test.js:20
        throw new Error("some error " + n);
```

So I tried to find a way to catch this error before it crashes node and before fast-check stops the predicate, but so far my current approach is not able to see the problem in time (as in the traces just above, the code supposed to catch the problem is called after the execution of all the predicates of fast-check):

```
let unhandledRejectionIntercepted = false;
process.on("unhandledRejection", (...args) => {
  unhandledRejectionIntercepted = true;
});

describe('schedule', () => {
  it('should fail with fast-check counterexample', async () => {
    await fc.assert(
      fc.asyncProperty(fc.scheduler(), async s => {
        unhandledRejectionIntercepted = false;
        s.schedule(Promise.resolve('p1')).then(() => {
          throw new Error('some error');
        });

        await s.waitAll();
        expext(unhandledRejectionIntercepted).toBe(false);
      })
    );
  });
});
```

**Comment by dubzzz** [comment] 2023-03-30 07:14
Given the remarks above, my recommendation would be to make sure never to fire orphan promises. Indeed if they never get awaited during the predicate, the predicate will not be able to know if they failed or not, so it should probably be:

```js
await fc.assert(
  fc.asyncProperty(fc.scheduler(), async (s) => {
    const p = s.schedule(Promise.resolve("p1")).then(() => {
      throw new Error("some error");
    });
  
    await s.waitAll();
    await Promise.all([p]); // all promises have to be awaited, otherwise we could face unhandled rejections
  })
);
```

**Comment by dubzzz** [comment] 2023-03-30 07:25
As a conclusion, I'd say this precise error is expected as fast-check cannot wait for results coming after the execution of the predicate or never awaited by it. The predicate we want to test here is similar to asking jest to say test1 failed in:

```js
test("test1", async () => {
  async function run() {
    expect(true).toBe(false);
  }
  run();
});
```

I'll check for the other issue, in the coming days. But the other might possibly have actionable options on fast-check's side. Anyway thanks for having reporting this one even if for now I don't think there is anything possible on fast-check's side as IMO it would mean being able to intercept any promise fired during the run and somehow wait for them and their results.

**Comment by dubzzz** [comment] 2023-04-25 18:32
Closing for now, expected behaviour

**Closed** 2023-04-25 18:32 UTC
Labels: 🐛 Bug Report
